### ISSUE TITLE
编译好的固件并不支持xray

### ISSUE THREAD

**Issue by Evenjine** [Mr-xn/k3_packages_backup#1]
宿主机：K3
固件：https://github.com/Mr-xn/k3_packages_backup/releases
ssrplus+里面的服务节点选项连xray都没有，看出已安装的包里面倒是有xray1.2。

**Comment by Mr-xn** [comment]
> 宿主机：K3
> 固件：https://github.com/Mr-xn/k3_packages_backup/releases
> ssrplus+里面的服务节点选项连xray都没有，看出已安装的包里面倒是有xray1.2。

添加服务器-服务器节点类型 选择 `vless` 即可看到 `xtls` 默认即运行 xray，添加 vmess 也是默认启用 xray ，你可以看日志.

**Comment by Evenjine** [comment]
> > 宿主机：K3
> > 固件：https://github.com/Mr-xn/k3_packages_backup/releases
> > ssrplus+里面的服务节点选项连xray都没有，看出已安装的包里面倒是有xray1.2。
> 
> 添加服务器-服务器节点类型 选择 `vless` 即可看到 `xtls` 默认即运行 xray，添加 vmess 也是默认启用 xray ，你可以看日志.

再试了一次，居然有了，谢谢🙏。
